local L = AceLibrary("AceLocale-2.2"):new("eePanels")

L:RegisterTranslations("esES", function() return
   {
      ["eePanels"]      = "eePanels",
      ["/eePanels"]     = "/eePanels",
      ["HideIcon"]      = "Ocultar el icono del minimapa",
      
      ["Reset?"]        = "\194\191Reestablecer?",
      ["Yes"]           = "S\195\173",
      ["No"]            = "No",
      
      ["Panel"]          = "Panel ",
      
      ["Solid"]         = "S\195\179lido",
      ["Gradient"]      = "Transici\195\179n",
      ["Horizontal"]    = "Horizontal",
      ["Vertical"]      = "Vertical",
      ["Background"]    = "Fondo",
      ["Low"]           = "Bajo",
      ["Medium"]        = "Medio",
      ["High"]          = "Alto",
      ["Dialog"]        = "Di\195\161logo",
      ["Tooltip"]       = "Tooltip",
      ["Disable"]       = "Desactivar",
      ["Blend"]         = "Mezcla",
      ["Add"]           = "A\195\177adir",
      ["Mod"]           = "Modificar",
      ["None"]          = "Ninguno",
      ["Dialog"]        = "Di\195\161logo",
      
      ["Lock"]                = "Bloquear paneles",
      ["LockDesc"]            = "Bloquea los paneles",
      ["NewPanel"]            = "Nuevo Panel",
      ["NewPanelDesc"]        = "Crea un nuevo panel",
      ["DefaultPanel"]        = "Usando Ajustes por Defecto",
      ["DefaultPanelDesc"]    = "Crea un nuevo panel usando los ajustes por defecto",
      ["GlobalPanel"]         = "Usando Ajustes Globales",
      ["GlobalPanelDesc"]     = "Crea un nuevo panel usando los ajustes globales",
      ["GlobalSettings"]      = "Ajustes Globales",
      ["GlobalSettingsDesc"]  = "Ajustes de panel globales",
      ["PanelSettings"]       = "Ajustes de Panel",
      ["PanelSettingsDesc"]   = "Ajustes de Panel",
      ["Reset"]               = "Reestablecer",
      ["ResetDesc"]           = "Reestablece los ajustes globales, y elimita todos los paneles",
      
      ["PanelName"]           = "Nombre",
      ["PanelNameDesc"]       = "Cambia el nombre a mostrar para el panel",
      ["PanelNameUsage"]      = "Introduce el nombre para el panel",
      ["BorderColor"]         = "Color del Borde",
      ["BorderColorDesc"]     = "Cambia el color del borde",
      ["BorderTexture"]       = "Textura del Borde",
      ["BorderTextureDesc"]   = "Cambia la textura del borde",
      ["BGColorStyle"]        = "Estilo del Color de Fondo",
      ["BGColorStyleDesc"]    = "Cambia el estilo del color de fondo",
      ["BGColor"]             = "Color de Fondo",
      ["BGColorDesc"]         = "Cambia el color de fondo",
      ["BGGradientColor"]     = "Color de fondo de transici\195\179n",
      ["BGGradientColorDesc"] = "Cambia el color de fondo de transici\195\179n",
      ["BGOrientation"]       = "Orientaci\195\179n de la transici\195\179n de Fondo",
      ["BGOrientationDesc"]   = "Cambia la orientaci\195\179n de la transici\195\179n del fondo",
      ["BGTexture"]           = "Textura de Fondo",
      ["BGTextureDesc"]       = "Cambia la textura de fondo",
      ["BGTextureUsage"]      = "Ubicaci\195\179n de la textura",
      ["BGBlend"]             = "Mezcla de fondo",
      ["BGBlendDesc"]         = "Cambia el modo mezcla del fondo",
      ["PanelLevel"]          = "Nivel",
      ["PanelLevelDesc"]      = "Cambia el nivel en el que se ubica el panel",
      ["PanelStrata"]         = "Estrato",
      ["PanelStrataDesc"]     = "Cambia el estrato en el que se ubica el panel",
      ["PanelWidth"]          = "Anchura",
      ["PanelWidthDesc"]      = "Cambia la anchura del panel",
      ["PanelHeight"]         = "Altura",
      ["PanelHeightDesc"]     = "Cambia la altura del panel",
      ["PanelX"]              = "Posici\195\179n Horizontal",
      ["PanelXDesc"]          = "Cambia la posici\195\179n horizontal del panel",
      ["PanelY"]              = "Posici\195\179n Vertical",
      ["PanelYDesc"]         = "Cambia la posici\195\179n horizontal del panel",
	["InterceptMouse"]		= "Intercept mouse clicks",
	["InterceptMouseDesc"]		= "Prevent the mouse from interacting with the game world through the panel",
      ["PanelRemove"]         = "Eliminar Panel",
      ["PanelRemoveDesc"]     = "Elimina el panel",
	["TextureShared"] = "Shared Texture", -- FIX ME
	["TextureSharedDesc"] = "Shared textures from SharedMedia", -- FIXME
	["TextureCustom"] = "Custom Texture", --FIXME
	["TextureCustomDesc"] = "Custom texture path", -- FIXME
   } 
end)