--Chinese Translate by Digmouse
--CWDG site: http://cwowaddon.com
local L = AceLibrary("AceLocale-2.2"):new("eePanels")

L:RegisterTranslations("zhCN", function() return 
{

	["HideIcon"] = "隐藏小地图按钮",

	["Reset?"]	= "重置设置?",
	["Yes"]	= "是",
	["No"]	= "否",

	["Panel"] = "面板",

	["Solid"] ="实心",
	["Gradient"] = "双色渐变",
	["Horizontal"] = "水平",
	["Vertical"] = "垂直",
	["Background"] = "背景",
	["Low"] = "低",
	["Medium"] = "中",
	["High"] = "高",
	["Dialog"] = "对话",
	["Tooltip"] = "提示",
	["Disable"] = "关闭",
	["Blend"] = "扭曲",
	["Add"] = "添加",
	["Mod"] = "模块",
	["None"] = "无",
	["Dialog"] = "对话",

	["Lock"]			= "锁定面板",
	["LockDesc"]			= "锁定面板",
	["Mode"]			= "高级模式",
	["ModeDesc"]			= "显示高级设置模式",
	["NewPanel"]			= "新面板",
	["NewPanelDesc"]		= "新建一个面板",
	["DefaultPanel"]		= "应用默认设置",
	["DefaultPanelDesc"]		= "使用默认设置创建一个新面板",
	["GlobalPanel"]			= "应用全局设置",
	["GlobalPanelDesc"]		= "使用全局设置创建一个新面板",
	["GlobalSettings"]		= "全局设置",
	["GlobalSettingsDesc"]		= "面板全局设置",
	["PanelSettings"]		= "面板设置",
	["PanelSettingsDesc"]		= "面板设置",
	["Reset"]			= "重置",
	["ResetDesc"]			= "重置全局设置并删除全部面板",

	["PanelName"]			= "名称",
	["PanelNameDesc"]		= "设置面板名称",
	["PanelNameUsage"]		= "输入面板名称",
	["BorderColor"]			= "边框颜色",
	["BorderColorDesc"]		= "改变边框颜色",
	["BorderTexture"]		= "边框材质",
	["BorderTextureDesc"]		= "改变边框材质",
	["BGColorStyle"]		= "背景色类型",
	["BGColorStyleDesc"]		= "改变背景色风格",
	["BGColor"]			= "背景色",
	["BGColorDesc"]			= "设置背景色",
	["BGGradientColor"]		= "背景渐变色",
	["BGGradientColorDesc"]		= "设置背景渐变色",
	["BGOrientation"]		= "背景色渐变方向",
	["BGOrientationDesc"]		= "设置背景色渐变方向",
	["BGTexture"]			= "背景材质",
	["BGTextureDesc"]		= "设置背景材质",
	["BGTextureUsage"]		= "材质路径",
	["BGBlend"]			= "背景扭曲",
	["BGBlendDesc"]			= "设置背景扭曲模式",
	["PanelLevel"]			= "等级",
	["PanelLevelDesc"]		= "设置面板依附等级",
	["PanelStrata"]			= "层",
	["PanelStrataDesc"]		= "设置面板依附的层级",
	["PanelWidth"]			= "宽度",
	["PanelWidthDesc"]		= "设置面板宽度",
	["PanelHeight"]			= "高度",
	["PanelHeightDesc"]		= "设置面板高度",
	["PanelX"]			= "水平位置",
	["PanelXDesc"]			= "改变面板水平位置",
	["PanelY"]			= "垂直位置",
	["PanelYDesc"]			= "改变面板垂直位置",
	["PanelParent"]			= "母体",
	["PanelParentDesc"]		= "面板依附的母框体",
	["InterceptMouse"]		= "阻止鼠标点击",
	["InterceptMouseDesc"]		= "防止鼠标点击穿过面板生效",
	["PanelRemove"]			= "移除面板",
	["PanelRemoveDesc"]		= "删除面板",
	
	["BGEdgeSize"]			= "边框外缘大小",
	["BGEdgeSizeDesc"]		= "边框外缘大小",
	["BGInset"]			= "背景填充幅度",
	["BGInsetDesc"]			= "内部材质填充大小",
	["BGTextureTiling"]		= "背景材质覆叠",
	["BGTextureTilingDesc"]		= "覆叠背景材质",
	["BGTileSize"]			= "背景覆叠大小",
	["BGTileSizeDessc"]		= "每一材质层的尺寸",
	["TextureShared"] = "共享材质",
	["TextureSharedDesc"] = "从SharedMedia共享材质",
	["TextureCustom"] = "自定义材质",
	["TextureCustomDesc"] = "自定义材质路径",
	
}
end)
